name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
          - runner: ubuntu-22.04
            target: x86
          - runner: ubuntu-22.04
            target: aarch64
          - runner: ubuntu-22.04
            target: armv7
          - runner: ubuntu-22.04
            target: s390x
          - runner: ubuntu-22.04
            target: ppc64le
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.9", "pypy3.10", "pypy3.11" ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform.target }}
          allow-prereleases: true
      - name: Create virtualenv
        shell: bash
        run: |
          python -m venv ${{ matrix.python-version }}
          echo "VENV_PATH=$GITHUB_WORKSPACE/${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/${{ matrix.python-version }}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        shell: bash
        run: |
          source ${{ matrix.python-version }}/bin/activate
          if [[ "${{ matrix.python-version }}" == "pypy3.11" ]]; then
            echo "Skipping pip upgrade for PyPy3.11"
          else
            python -m pip install --upgrade pip
          fi
          python -m pip install -U maturin

      - name: Build wheels
        shell: bash
        run: |
          source ${{ matrix.python-version }}/bin/activate
          maturin build \
          --release \
          --out target/wheels \
          --find-interpreter \
          --target ${{ matrix.platform.target }}
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.platform.target }}-py${{ matrix.python-version }}
          path: target/wheels
          overwrite: true

  musllinux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64
          - runner: ubuntu-22.04
            target: x86
          - runner: ubuntu-22.04
            target: aarch64
          - runner: ubuntu-22.04
            target: armv7
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.9", "pypy3.10", "pypy3.11" ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Create virtualenv
        shell: bash
        run: |
          python -m venv ${{ matrix.python-version }}
          echo "VENV_PATH=$GITHUB_WORKSPACE/${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/${{ matrix.python-version }}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        shell: bash
        run: |
          source ${{ matrix.python-version }}/bin/activate
          if [[ "${{ matrix.python-version }}" == "pypy3.11" ]]; then
            echo "Skipping pip upgrade for PyPy3.11"
          else
            python -m pip install --upgrade pip
          fi
          python -m pip install -U maturin

      - name: Build wheels
        shell: bash
        run: |
          source ${{ matrix.python-version }}/bin/activate
          maturin build \
          --release \
          --out target/wheels \
          --find-interpreter \
          --target ${{ matrix.platform.target }}
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-musllinux-${{ matrix.platform.target }}-py${{ matrix.python-version }}
          path: target/wheels
          overwrite: true

  windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x64
          - runner: windows-latest
            target: x86
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.9", "pypy3.10", "pypy3.11" ]
        exclude:
          - platform:
              runner: windows-latest
              target: x86
            python-version: "pypy3.9"
          - platform:
              runner: windows-latest
              target: x86
            python-version: "pypy3.10"
          - platform:
              runner: windows-latest
              target: x86
            python-version: "pypy3.11"

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.platform.target }}
          allow-prereleases: true
      - name: Create virtualenv
        shell: bash
        run: |
          python -m venv ${{ matrix.python-version }}
          echo "VENV_PATH=$GITHUB_WORKSPACE/${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/${{ matrix.python-version }}/Scripts" >> $GITHUB_PATH
      - name: Install dependencies
        shell: bash
        run: |
          source ${{ matrix.python-version }}/Scripts/activate
          if [[ "${{ matrix.python-version }}" == "pypy3.11" ]]; then
            echo "Skipping pip upgrade for PyPy3.11"
          else
            python -m pip install --upgrade pip
          fi
          python -m pip install -U maturin

      - name: Build wheels
        shell: bash
        run: |
          source ${{ matrix.python-version }}/Scripts/activate
          maturin build \
          --release \
          --out target/wheels \
          --find-interpreter \
          --target ${{ matrix.platform.target }}
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows-${{ matrix.platform.target }}-py${{ matrix.python-version }}
          path: target/wheels
          overwrite: true

  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-13
            target: x86_64
          - runner: macos-14
            target: aarch64
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.9", "pypy3.10", "pypy3.11" ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Create virtualenv
        shell: bash
        run: |
          python -m venv ${{ matrix.python-version }}
          echo "VENV_PATH=$GITHUB_WORKSPACE/${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/${{ matrix.python-version }}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        shell: bash
        run: |
          source ${{ matrix.python-version }}/bin/activate
          if [[ "${{ matrix.python-version }}" == "pypy3.11" ]]; then
            echo "Skipping pip upgrade for PyPy3.11"
          else
            python -m pip install --upgrade pip
          fi
          python -m pip install -U maturin

      - name: Build wheels
        shell: bash
        run: |
          source ${{ matrix.python-version }}/bin/activate
          maturin build \
          --release \
          --out target/wheels \
          --find-interpreter \
          --target ${{ matrix.platform.target }}
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.platform.target }}-py${{ matrix.python-version }}
          path: target/wheels
          overwrite: true

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out target/wheels
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: target/wheels

  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
    needs: [linux, musllinux, windows, macos, sdist]
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'wheels-*/*'
      - name: Publish to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --non-interactive --skip-existing wheels-*/*
