name: Cross-platform sanity check

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "3.15", "pypy3.11"]
    continue-on-error: ${{ matrix.allow-failure || false }}
    steps:
      - uses: actions/checkout@v7

      - name: Install UV
        uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install ${{ matrix.python-version }}

      - name: Create virtualenv and install dependencies
        shell: bash
        run: |
          uv venv
          uv pip install -U setuptools wheel maturin pytest virtualenv
          uv run maturin develop --release

      - name: Test
        shell: bash
        run: uv run pytest
