name: Cross-platform sanity check

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.9", "pypy3.10" ]
        exclude:
          - os: ubuntu-latest
            python-version: "3.14"
          - os: macos-latest
            python-version: "3.14"
          - os: windows-latest
            python-version: "3.14"
        include:
          - os: ubuntu-latest
            python-version: "3.14"
            allow-failure: true
          - os: macos-latest
            python-version: "3.14"
            allow-failure: true
          - os: windows-latest
            python-version: "3.14"
            allow-failure: true
    continue-on-error: ${{ matrix.allow-failure || false }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Create virtualenv and install package
        shell: bash
        run: |
          python -m venv env
      - name: Install build and test deps (Windows)
        if: runner.os == 'Windows'
        run: |
          env\Scripts\python -m pip install --upgrade pip
          env\Scripts\python -m pip install -U setuptools wheel maturin pytest
          env\Scripts\python -m maturin develop --release
      - name: Install build and test deps (Unix)
        if: runner.os != 'Windows'
        run: |
          env/bin/python -m pip install --upgrade pip
          env/bin/python -m pip install -U setuptools wheel maturin pytest
          env/bin/python -m maturin develop --release
      - name: Test (Windows)
        if: runner.os == 'Windows'
        run: |
          env\Scripts\python -m pytest -q
      - name: Test (Unix)
        if: runner.os != 'Windows'
        run: |
          env/bin/python -m pytest -q
